/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.BemDAO;
import DAO.ResidenciaDAO;
import Motor.ControleSolicitacao;
import dadosResidencia.Bem;
import dadosResidencia.Residencia;
import excecao.ExceptionEmptySpace;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Montanha
 */
public class Painel_Candidato extends javax.swing.JFrame {

    ControleSolicitacao controlador;

    /**
     * Creates new form Painel_Corretor
     */
    public Painel_Candidato() {
        initComponents();
        painelSolicitacao.setVisible(false);
        editar.setVisible(false);
        nova.setVisible(false);
        cancelarSolicitacao.setVisible(false);
        painelServico.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        popupMenu1 = new java.awt.PopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        solicitarSeguro = new javax.swing.JButton();
        minhasResidencias = new javax.swing.JButton();
        contratarServico = new javax.swing.JButton();
        relatarSinistro = new javax.swing.JButton();
        painelP = new javax.swing.JPanel();
        painelServico = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Encanador = new javax.swing.JCheckBox();
        chaveiro = new javax.swing.JCheckBox();
        eletricista = new javax.swing.JCheckBox();
        enviarServico = new javax.swing.JButton();
        cancelarServico = new javax.swing.JButton();
        painelSolicitacao = new javax.swing.JPanel();
        cep = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        descBem = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        exibir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        comodos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        banheiro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        garagem = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        andares = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        descRes = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        anoC = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        areat = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        localizacaoP = new javax.swing.JSlider();
        l = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        terrenoP = new javax.swing.JSlider();
        t = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        estruturaA = new javax.swing.JSlider();
        e = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        areaConstruida = new javax.swing.JTextField(4);
        jSeparator1 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        editar = new javax.swing.JButton();
        cancelarSolicitacao = new javax.swing.JButton();
        nova = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        sairButton = new javax.swing.JButton();
        buttonVisualizarSolicitacao = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solicitarSeguro.setBackground(new java.awt.Color(0, 51, 51));
        solicitarSeguro.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        solicitarSeguro.setForeground(new java.awt.Color(255, 255, 255));
        solicitarSeguro.setText("Solicitação Seguro de Residência");
        solicitarSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarSeguroActionPerformed(evt);
            }
        });
        getContentPane().add(solicitarSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 40));
        solicitarSeguro.getAccessibleContext().setAccessibleDescription("");

        minhasResidencias.setBackground(new java.awt.Color(0, 51, 51));
        minhasResidencias.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        minhasResidencias.setForeground(new java.awt.Color(255, 255, 255));
        minhasResidencias.setText("Minhas Residências");
        minhasResidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minhasResidenciasActionPerformed(evt);
            }
        });
        getContentPane().add(minhasResidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 40));

        contratarServico.setBackground(new java.awt.Color(0, 51, 51));
        contratarServico.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        contratarServico.setForeground(new java.awt.Color(255, 255, 255));
        contratarServico.setText("Contratar Serviço");
        contratarServico.setToolTipText("");
        contratarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarServicoActionPerformed(evt);
            }
        });
        getContentPane().add(contratarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 40));

        relatarSinistro.setBackground(new java.awt.Color(0, 51, 51));
        relatarSinistro.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        relatarSinistro.setForeground(new java.awt.Color(255, 255, 255));
        relatarSinistro.setText("Relatar Sinistro");
        relatarSinistro.setToolTipText("");
        relatarSinistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatarSinistroActionPerformed(evt);
            }
        });
        getContentPane().add(relatarSinistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 40));

        painelP.setBackground(new java.awt.Color(204, 204, 255));
        painelP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelServico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel4.setText("Qual serviço deseja solicitar?");
        painelServico.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        Encanador.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        Encanador.setText("Encanador");
        painelServico.add(Encanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        chaveiro.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        chaveiro.setText("Chaveiro");
        painelServico.add(chaveiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        eletricista.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        eletricista.setText("Eletricista");
        eletricista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletricistaActionPerformed(evt);
            }
        });
        painelServico.add(eletricista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        enviarServico.setBackground(new java.awt.Color(151, 53, 255));
        enviarServico.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        enviarServico.setForeground(new java.awt.Color(255, 255, 255));
        enviarServico.setText("Enviar");
        painelServico.add(enviarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        cancelarServico.setBackground(new java.awt.Color(153, 0, 0));
        cancelarServico.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        cancelarServico.setForeground(new java.awt.Color(255, 255, 255));
        cancelarServico.setText("Cancelar");
        cancelarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarServicoActionPerformed(evt);
            }
        });
        painelServico.add(cancelarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        painelP.add(painelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 350, 240));

        painelSolicitacao.setBackground(new java.awt.Color(255, 255, 255));
        painelSolicitacao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });
        painelSolicitacao.add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 62, 77, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel2.setText("CEP:");
        painelSolicitacao.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 39, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel5.setText("UF:");
        painelSolicitacao.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 39, -1, -1));

        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });
        painelSolicitacao.add(uf, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 62, 77, -1));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel7.setText("Cidade:");
        painelSolicitacao.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 39, -1, -1));

        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        painelSolicitacao.add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 62, 86, -1));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel8.setText("Bairro:");
        painelSolicitacao.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 39, -1, -1));

        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });
        painelSolicitacao.add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 62, 97, -1));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel9.setText("Rua:");
        painelSolicitacao.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 39, -1, -1));

        rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaActionPerformed(evt);
            }
        });
        painelSolicitacao.add(rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 62, 110, -1));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel10.setText("Número:");
        painelSolicitacao.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 39, -1, -1));

        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        painelSolicitacao.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 62, 41, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Bem:");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 11, -1, -1));

        jLabel20.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Descrição:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Valor:");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));
        jPanel6.add(descBem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 100, -1));
        jPanel6.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 58, 60, -1));

        add.setBackground(new java.awt.Color(151, 53, 255));
        add.setFont(new java.awt.Font("Sylfaen", 0, 11)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Adicionar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel6.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 11, 80, -1));

        remover.setBackground(new java.awt.Color(153, 0, 0));
        remover.setFont(new java.awt.Font("Sylfaen", 0, 11)); // NOI18N
        remover.setForeground(new java.awt.Color(255, 255, 255));
        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });
        jPanel6.add(remover, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 41, 79, -1));

        exibir.setBackground(new java.awt.Color(151, 53, 255));
        exibir.setFont(new java.awt.Font("Sylfaen", 0, 11)); // NOI18N
        exibir.setForeground(new java.awt.Color(255, 255, 255));
        exibir.setText("Exibir");
        exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirActionPerformed(evt);
            }
        });
        jPanel6.add(exibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 70, 79, -1));

        painelSolicitacao.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 310, 100));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(comodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 61, -1));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cômodos:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel5.add(banheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 60, 61, -1));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Banheiro:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));
        jPanel5.add(garagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 60, 61, -1));

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Garagem:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));
        jPanel5.add(andares, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 60, 61, -1));

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Andares:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quantidade:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 11, -1, -1));

        painelSolicitacao.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 290, 100));

        jLabel18.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel18.setText("Descrição:");
        painelSolicitacao.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        painelSolicitacao.add(descRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 289, -1));

        jLabel16.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel16.setText("Ano Construção:");
        painelSolicitacao.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        anoC.setMinimumSize(new java.awt.Dimension(4, 4));
        anoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoCActionPerformed(evt);
            }
        });
        painelSolicitacao.add(anoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 81, -1));

        jLabel17.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel17.setText("Área Total:");
        painelSolicitacao.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, -1, -1));

        areat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areatActionPerformed(evt);
            }
        });
        painelSolicitacao.add(areat, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 61, -1));

        jLabel24.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel24.setText("Localização Perigosa:");
        painelSolicitacao.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        localizacaoP.setMaximum(10);
        localizacaoP.setValue(5);
        localizacaoP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        localizacaoP.setName(""); // NOI18N
        localizacaoP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                localizacaoPStateChanged(evt);
            }
        });
        localizacaoP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                localizacaoPMouseDragged(evt);
            }
        });
        painelSolicitacao.add(localizacaoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 305, 108, 14));

        l.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        l.setText("5");
        painelSolicitacao.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 305, -1, -1));

        jLabel25.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel25.setText("Terreno Perigoso:");
        painelSolicitacao.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        terrenoP.setMaximum(10);
        terrenoP.setSnapToTicks(true);
        terrenoP.setValue(5);
        terrenoP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                terrenoPStateChanged(evt);
            }
        });
        painelSolicitacao.add(terrenoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 305, 129, 14));

        t.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        t.setText("5");
        painelSolicitacao.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 305, -1, -1));

        jLabel26.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel26.setText("Estrutura Ameaçada:");
        painelSolicitacao.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 108, -1));

        estruturaA.setMaximum(10);
        estruturaA.setValue(5);
        estruturaA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        estruturaA.setName(""); // NOI18N
        estruturaA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                estruturaAStateChanged(evt);
            }
        });
        painelSolicitacao.add(estruturaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 305, 108, 14));

        e.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        e.setText("5");
        painelSolicitacao.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 305, -1, -1));

        cancelar.setBackground(new java.awt.Color(153, 0, 0));
        cancelar.setFont(new java.awt.Font("Sylfaen", 0, 11)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        painelSolicitacao.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 340, -1, -1));

        enviar.setBackground(new java.awt.Color(151, 53, 255));
        enviar.setFont(new java.awt.Font("Sylfaen", 0, 11)); // NOI18N
        enviar.setForeground(new java.awt.Color(255, 255, 255));
        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        painelSolicitacao.add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 340, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel1.setText("Dados:");
        painelSolicitacao.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 10));

        areaConstruida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaConstruidaActionPerformed(evt);
            }
        });
        painelSolicitacao.add(areaConstruida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 80, -1));
        painelSolicitacao.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 690, 60));

        jLabel22.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        jLabel22.setText("Área Construida:");
        painelSolicitacao.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setText("Endereço:");
        painelSolicitacao.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        painelSolicitacao.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 122, 690, 260));

        painelP.add(painelSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 690, 380));

        editar.setBackground(new java.awt.Color(151, 53, 255));
        editar.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setText("Editar Solicitação");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        painelP.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 160, -1));

        cancelarSolicitacao.setBackground(new java.awt.Color(153, 0, 0));
        cancelarSolicitacao.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        cancelarSolicitacao.setForeground(new java.awt.Color(255, 255, 255));
        cancelarSolicitacao.setText("Cancelar Solicitação");
        cancelarSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarSolicitacaoActionPerformed(evt);
            }
        });
        painelP.add(cancelarSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        nova.setBackground(new java.awt.Color(151, 53, 255));
        nova.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        nova.setForeground(new java.awt.Color(255, 255, 255));
        nova.setText("Nova Solicitação");
        nova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaActionPerformed(evt);
            }
        });
        painelP.add(nova, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 160, -1));

        bg.setText("jLabel3");
        painelP.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sairButton.setBackground(new java.awt.Color(153, 0, 0));
        sairButton.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        sairButton.setForeground(new java.awt.Color(255, 255, 255));
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        painelP.add(sairButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 80, 30));

        buttonVisualizarSolicitacao.setBackground(new java.awt.Color(151, 53, 255));
        buttonVisualizarSolicitacao.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        buttonVisualizarSolicitacao.setForeground(new java.awt.Color(255, 255, 255));
        buttonVisualizarSolicitacao.setText("Visualizar Solicitações");
        buttonVisualizarSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarSolicitacaoActionPerformed(evt);
            }
        });
        painelP.add(buttonVisualizarSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 220, 40));

        getContentPane().add(painelP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1240, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minhasResidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minhasResidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minhasResidenciasActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void solicitarSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarSeguroActionPerformed
        /*Tela_ListaSolicitacoes telaSolicitacoes = new Tela_ListaSolicitacoes();
        telaSolicitacoes.setVisible(true);
        dispose();*/
        this.controlador = new ControleSolicitacao();
        editar.setVisible(true);
        nova.setVisible(true);
        cancelarSolicitacao.setVisible(true);
    }//GEN-LAST:event_solicitarSeguroActionPerformed

    private void relatarSinistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatarSinistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relatarSinistroActionPerformed

    private void contratarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarServicoActionPerformed
        painelServico.setVisible(true);
        painelSolicitacao.setVisible(false);
        cancelar.setVisible(false);
        editar.setVisible(false);
        nova.setVisible(false);
    }//GEN-LAST:event_contratarServicoActionPerformed

    private void novaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaActionPerformed
        painelSolicitacao.setVisible(true);
    }//GEN-LAST:event_novaActionPerformed

    private void cancelarSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarSolicitacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarSolicitacaoActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        //recuperar dados da solicitação que el deseja editar
        painelSolicitacao.setVisible(true);
    }//GEN-LAST:event_editarActionPerformed

    private void areaConstruidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaConstruidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaConstruidaActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        try {
            ExceptionEmptySpace.informaDado(cep.getText()); //parse long
            ExceptionEmptySpace.informaDado(uf.getText());
            ExceptionEmptySpace.informaDado(cidade.getText());
            ExceptionEmptySpace.informaDado(bairro.getText());
            ExceptionEmptySpace.informaDado(rua.getText());
            ExceptionEmptySpace.informaDado(numero.getText());//parse int
            ExceptionEmptySpace.informaDado(comodos.getText());//parse int
            ExceptionEmptySpace.informaDado(banheiro.getText());///parse int
            ExceptionEmptySpace.informaDado(garagem.getText());//parse int
            ExceptionEmptySpace.informaDado(andares.getText());///parse int
            ExceptionEmptySpace.informaDado(areat.getText());//parse int
            ExceptionEmptySpace.informaDado(anoC.getText());///parse int
            ExceptionEmptySpace.informaDado(descRes.getText());
            ExceptionEmptySpace.informaDado(areaConstruida.getText());

            int numeroCandidato = Integer.parseInt(numero.getText());
            long cepCandidato = Long.parseLong(cep.getText());

            int comodosCandidato = Integer.parseInt(comodos.getText());
            int banheiroCandidato = Integer.parseInt(banheiro.getText());
            int garagemCandidato = Integer.parseInt(garagem.getText());
            int andaresCandidato = Integer.parseInt(andares.getText());
            float areaT = Float.parseFloat(areat.getText());
            double areaC = Float.parseFloat(areaConstruida.getText());

            int anoConstrucao = Integer.parseInt(anoC.getText());

            int localizacao = localizacaoP.getValue();
            int terreno = terrenoP.getValue();
            int estrutura = estruturaA.getValue();

            controlador.registrarSolicitacao(uf.getText(), cidade.getText(), bairro.getText(), descRes.getText(),
                    numeroCandidato, cepCandidato, comodosCandidato, banheiroCandidato, garagemCandidato, areaT, areaC, andaresCandidato,
                    anoConstrucao, rua.getText(), localizacao, terreno, estrutura);

            JOptionPane.showMessageDialog(painelP, "\n Sua solicitação foi enviada para avaliação!");
            //JOptionPane.showMessageDialog(painelP, "/n" + controlador.getSolicitacao().toString());//ler do banco 
            painelSolicitacao.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(painelP, "Por favor insira todas as informações");
        }
        
    }//GEN-LAST:event_enviarActionPerformed
    public void esvaziarCampos(){
        
    }
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.esvaziarCampos();
        painelSolicitacao.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void estruturaAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_estruturaAStateChanged
        e.setText(Integer.toString(estruturaA.getValue()));
    }//GEN-LAST:event_estruturaAStateChanged

    private void terrenoPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_terrenoPStateChanged
        t.setText(Integer.toString(terrenoP.getValue()));
    }//GEN-LAST:event_terrenoPStateChanged

    private void localizacaoPMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localizacaoPMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_localizacaoPMouseDragged

    private void localizacaoPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_localizacaoPStateChanged
        l.setText(Integer.toString(localizacaoP.getValue()));
    }//GEN-LAST:event_localizacaoPStateChanged

    private void areatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areatActionPerformed

    private void exibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirActionPerformed
        
        JOptionPane.showMessageDialog(painelP, "Bens: \r\n" + controlador.getBens().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_exibirActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        try {
            String removido = JOptionPane.showInputDialog(painelP, "Digite o nome do Bem que deseja Remover! \r\n" + controlador.getBens().toString());
            Bem temp = null;
            for(int i = 0; i<controlador.getBens().size(); i++){
                if(controlador.getBens().get(i).getDescricaoBem().equalsIgnoreCase(removido)){
                    temp = controlador.getBens().get(i);
                    break;
                }
            }
            if (controlador.getBens().remove(temp)) {
                JOptionPane.showMessageDialog(null, "Bem: \r\n" + removido + " Removido!");

            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Este bem não foi adicionado!");
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Nenhum bem foi encontrado!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_removerActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            ExceptionEmptySpace.informaDado(descBem.getText());
            ExceptionEmptySpace.informaDado(valor.getText());
            if (controlador.registraBemLista(Float.parseFloat(valor.getText()), descBem.getText())) {
                descBem.setText("");
                valor.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed
    public void gerarBackground() {
        String pasta = System.getProperty("user.dir");
        bg.setIcon(new ImageIcon(pasta + "/src/imagens/barraSup.jpg"));

    }
    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ruaActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void buttonVisualizarSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVisualizarSolicitacaoActionPerformed
        Tela_ListaSolicitacaoCandidato listaSolicitacaoCandidato = new Tela_ListaSolicitacaoCandidato();
        listaSolicitacaoCandidato.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonVisualizarSolicitacaoActionPerformed

    private void anoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoCActionPerformed
       
    }//GEN-LAST:event_anoCActionPerformed

    private void eletricistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eletricistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eletricistaActionPerformed

    private void cancelarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel_Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel_Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel_Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel_Candidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Painel_Candidato painel = new Painel_Candidato();
                painel.gerarBackground();
                painel.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Encanador;
    private javax.swing.JButton add;
    private javax.swing.JTextField andares;
    private javax.swing.JTextField anoC;
    private javax.swing.JTextField areaConstruida;
    private javax.swing.JTextField areat;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField banheiro;
    private javax.swing.JLabel bg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton buttonVisualizarSolicitacao;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelarServico;
    private javax.swing.JButton cancelarSolicitacao;
    private javax.swing.JTextField cep;
    private javax.swing.JCheckBox chaveiro;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField comodos;
    private javax.swing.JButton contratarServico;
    private javax.swing.JTextField descBem;
    private javax.swing.JTextField descRes;
    private javax.swing.JLabel e;
    private javax.swing.JButton editar;
    private javax.swing.JCheckBox eletricista;
    private javax.swing.JButton enviar;
    private javax.swing.JButton enviarServico;
    private javax.swing.JSlider estruturaA;
    private javax.swing.JButton exibir;
    private javax.swing.JTextField garagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l;
    private javax.swing.JSlider localizacaoP;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JButton minhasResidencias;
    private javax.swing.JButton nova;
    private javax.swing.JTextField numero;
    private javax.swing.JPanel painelP;
    private javax.swing.JPanel painelServico;
    private javax.swing.JPanel painelSolicitacao;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton relatarSinistro;
    private javax.swing.JButton remover;
    private javax.swing.JTextField rua;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton solicitarSeguro;
    private javax.swing.JLabel t;
    private javax.swing.JSlider terrenoP;
    private javax.swing.JTextField uf;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
