/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Montanha
 */
public class Painel_Corretor extends javax.swing.JFrame {

    int visivel = 0;

    /**
     * Creates new form Painel_Corretor
     */
    public Painel_Corretor() {
        initComponents();
        jLabelBemVindoCorretor.setVisible(true);
        buttonConfiguracao.setVisible(true);
        jComboBoxOpcoesCorretor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avaliarSolicitacaoButton = new javax.swing.JButton();
        visualizarSolicitacoesButton = new javax.swing.JButton();
        avaliarSinistroButton = new javax.swing.JButton();
        gerenciarServicosButton = new javax.swing.JButton();
        jLabelBemVindoCorretor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxOpcoesCorretor = new javax.swing.JComboBox<>();
        buttonConfiguracao = new javax.swing.JButton();
        jLabelBarraSup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        avaliarSolicitacaoButton.setBackground(new java.awt.Color(255, 255, 255));
        avaliarSolicitacaoButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        avaliarSolicitacaoButton.setForeground(new java.awt.Color(110, 48, 110));
        avaliarSolicitacaoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contract.png"))); // NOI18N
        avaliarSolicitacaoButton.setText("Avaliar Residência        ");
        avaliarSolicitacaoButton.setBorder(null);
        avaliarSolicitacaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        avaliarSolicitacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarSolicitacaoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(avaliarSolicitacaoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 180, 40));
        avaliarSolicitacaoButton.getAccessibleContext().setAccessibleDescription("");

        visualizarSolicitacoesButton.setBackground(new java.awt.Color(255, 255, 255));
        visualizarSolicitacoesButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        visualizarSolicitacoesButton.setForeground(new java.awt.Color(110, 48, 110));
        visualizarSolicitacoesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/study.png"))); // NOI18N
        visualizarSolicitacoesButton.setText("Visualizar Solicitações");
        visualizarSolicitacoesButton.setToolTipText("");
        visualizarSolicitacoesButton.setBorder(null);
        visualizarSolicitacoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarSolicitacoesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(visualizarSolicitacoesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 40));

        avaliarSinistroButton.setBackground(new java.awt.Color(255, 255, 255));
        avaliarSinistroButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        avaliarSinistroButton.setForeground(new java.awt.Color(110, 48, 110));
        avaliarSinistroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/danger.png"))); // NOI18N
        avaliarSinistroButton.setText("Avaliar Sinistro            ");
        avaliarSinistroButton.setBorder(null);
        avaliarSinistroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliarSinistroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(avaliarSinistroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, 40));

        gerenciarServicosButton.setBackground(new java.awt.Color(255, 255, 255));
        gerenciarServicosButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        gerenciarServicosButton.setForeground(new java.awt.Color(110, 48, 110));
        gerenciarServicosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tools.png"))); // NOI18N
        gerenciarServicosButton.setText("Gerenciar Serviços ");
        getContentPane().add(gerenciarServicosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 180, 40));

        jLabelBemVindoCorretor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelBemVindoCorretor.setText("Bem-Vindo ao Painel do Corretor");
        getContentPane().add(jLabelBemVindoCorretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 400, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo-roxoMenu.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 490));

        jComboBoxOpcoesCorretor.setBackground(new java.awt.Color(110, 48, 110));
        jComboBoxOpcoesCorretor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBoxOpcoesCorretor.setForeground(new java.awt.Color(110, 48, 110));
        jComboBoxOpcoesCorretor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minha conta", "Sair" }));
        jComboBoxOpcoesCorretor.setToolTipText("");
        jComboBoxOpcoesCorretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpcoesCorretorActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxOpcoesCorretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 130, 30));

        buttonConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/setting.png"))); // NOI18N
        buttonConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfiguracaoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConfiguracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 40, -1));

        jLabelBarraSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem Título-1.jpg"))); // NOI18N
        getContentPane().add(jLabelBarraSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizarSolicitacoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarSolicitacoesButtonActionPerformed
        Tela_ListaSolicitacaoSeguro telaListaSeguro = new Tela_ListaSolicitacaoSeguro();
        if (telaListaSeguro.readTable() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Não possui solicitações para avaliar.", "Alerta", JOptionPane.CLOSED_OPTION);
        } else {
            telaListaSeguro.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_visualizarSolicitacoesButtonActionPerformed

    private void avaliarSinistroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarSinistroButtonActionPerformed
        Tela_ListaDeSinistro telaListaSinistro = new Tela_ListaDeSinistro();
        if (telaListaSinistro.readTable() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Não possui sinistros para avaliar.", "Alerta", JOptionPane.CLOSED_OPTION);
        } else {
            telaListaSinistro.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_avaliarSinistroButtonActionPerformed

    private void avaliarSolicitacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaliarSolicitacaoButtonActionPerformed
        Tela_ListaSolicitacoes telSolicitacao = new Tela_ListaSolicitacoes();
        if (telSolicitacao.readTable() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Não possui residencias para avaliar.", "Alerta", JOptionPane.CLOSED_OPTION);
        } else {
            telSolicitacao.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_avaliarSolicitacaoButtonActionPerformed

    private void buttonConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfiguracaoActionPerformed
        jComboBoxOpcoesCorretor.setVisible(true);
        if (visivel == 1) {
            jComboBoxOpcoesCorretor.setVisible(false);
            visivel = 0;
        } else {
            visivel++;
        }
    }//GEN-LAST:event_buttonConfiguracaoActionPerformed

    private void jComboBoxOpcoesCorretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpcoesCorretorActionPerformed
        String opcaoEscolhida;
        opcaoEscolhida = jComboBoxOpcoesCorretor.getSelectedItem().toString();
        if (opcaoEscolhida.equalsIgnoreCase("Minha conta")) {
            Tela_cadastraPessoa telaCadastro = new Tela_cadastraPessoa();
            jComboBoxOpcoesCorretor.setVisible(false);
            telaCadastro.setVisible(true);
            dispose();
        } else if (opcaoEscolhida.equalsIgnoreCase("Sair")) {
            Tela_Login telaLogin = new Tela_Login();
            telaLogin.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jComboBoxOpcoesCorretorActionPerformed

    public void gerarBackground() {
        String pasta = System.getProperty("user.dir");
        jLabelBarraSup.setIcon(new ImageIcon(pasta + "/src/imagens/Sem Título-1.jpg"));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel_Corretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel_Corretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel_Corretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel_Corretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Painel_Corretor painelCorretor = new Painel_Corretor();
                painelCorretor.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliarSinistroButton;
    private javax.swing.JButton avaliarSolicitacaoButton;
    private javax.swing.JButton buttonConfiguracao;
    private javax.swing.JButton gerenciarServicosButton;
    private javax.swing.JComboBox<String> jComboBoxOpcoesCorretor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBarraSup;
    private javax.swing.JLabel jLabelBemVindoCorretor;
    private javax.swing.JButton visualizarSolicitacoesButton;
    // End of variables declaration//GEN-END:variables
}
