/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DadosResidencia.SolicitacaoSeguro;
import Motor.Motor;
import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import sun.awt.im.InputMethodJFrame;

/**
 *
 * @author Matheus Montanha
 */
public class Tela_EnviarSolicitacao extends javax.swing.JFrame {

    Motor motor = new Motor();

    /**
     * Creates new form Tela_EnviarSolicitacao
     */
    public Tela_EnviarSolicitacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmarSolicitacaiButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxAnoSolicitacao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxNivelLocalzacaoPerigosa1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ComboBoxNivelTerrenoPerigosa1 = new javax.swing.JComboBox<>();
        ComboBoxNivelEstruturaAmeacada1 = new javax.swing.JComboBox<>();
        ComboBoxDiaSolicitacao = new javax.swing.JComboBox<>();
        ComboBoxMesSolicitacao = new javax.swing.JComboBox<>();
        ComboBoxAnoVisita = new javax.swing.JComboBox<>();
        ComboBoxResultadoSolicitacao = new javax.swing.JComboBox<>();
        ComboBoxMesVisita = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        ComboBoxDiaVisita1 = new javax.swing.JComboBox<>();
        valorSolicitacao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivoReprovacao = new javax.swing.JTextPane();
        cancelarButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmarSolicitacaiButton.setText("Confirmar");
        confirmarSolicitacaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarSolicitacaiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarSolicitacaiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Localização Perigosa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        ComboBoxAnoSolicitacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        getContentPane().add(ComboBoxAnoSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Motivo reprovação:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 30));

        ComboBoxNivelLocalzacaoPerigosa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "9", "8", "7", "6", "5", "4", "3", "2", "1" }));
        ComboBoxNivelLocalzacaoPerigosa1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(ComboBoxNivelLocalzacaoPerigosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Terreno Perigoso:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Estrutura Ameaçada:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Data da Solicitação:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Data da visita:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Valor da solicitação:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Aprovada solicitação:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 30));

        ComboBoxNivelTerrenoPerigosa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "9", "8", "7", "6", "5", "4", "3", "2", "1" }));
        getContentPane().add(ComboBoxNivelTerrenoPerigosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        ComboBoxNivelEstruturaAmeacada1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "9", "8", "7", "6", "5", "4", "3", "2", "1" }));
        getContentPane().add(ComboBoxNivelEstruturaAmeacada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        ComboBoxDiaSolicitacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(ComboBoxDiaSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        ComboBoxMesSolicitacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" }));
        getContentPane().add(ComboBoxMesSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        ComboBoxAnoVisita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        getContentPane().add(ComboBoxAnoVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        ComboBoxResultadoSolicitacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprovada", "Recusada" }));
        getContentPane().add(ComboBoxResultadoSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        ComboBoxMesVisita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez" }));
        getContentPane().add(ComboBoxMesVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel9.setText("R$");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 20, 30));

        ComboBoxDiaVisita1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(ComboBoxDiaVisita1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        getContentPane().add(valorSolicitacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 60, -1));

        jScrollPane1.setViewportView(motivoReprovacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 160, 60));

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esse sim.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarSolicitacaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarSolicitacaiButtonActionPerformed
        int localizacaoPerigosa = Integer.parseInt(ComboBoxNivelLocalzacaoPerigosa1.getSelectedItem().toString());
        int terrenoPerigo = Integer.parseInt(ComboBoxNivelTerrenoPerigosa1.getSelectedItem().toString());
        int estruturaAmeacada = Integer.parseInt(ComboBoxNivelEstruturaAmeacada1.getSelectedItem().toString());
        String dataSolicitacao = ComboBoxDiaSolicitacao.getSelectedItem().toString() + "/" + ComboBoxMesSolicitacao.getSelectedItem().toString() + "/" + ComboBoxAnoSolicitacao.getSelectedItem().toString();
        String dataVisita = ComboBoxDiaVisita1.getSelectedItem().toString() + "/" + ComboBoxMesVisita.getSelectedItem().toString() + "/" + ComboBoxAnoVisita.getSelectedItem().toString();
        double valorDeSolicitacao = Double.parseDouble(valorSolicitacao.getText());
        String motivoDeReprovacao = motivoReprovacao.getText();
        boolean aprovadaResidencia;
        if (ComboBoxResultadoSolicitacao.getSelectedItem().toString().contains("Aprovada")) {
            aprovadaResidencia = true;
        } else {
            aprovadaResidencia = false;
        }
        SolicitacaoSeguro novaSolicitacao = new SolicitacaoSeguro(localizacaoPerigosa, terrenoPerigo, estruturaAmeacada, dataSolicitacao, dataVisita, valorDeSolicitacao, aprovadaResidencia, motivoDeReprovacao);
        if (motor.enviarSoliciacao(novaSolicitacao)) {
            System.out.println("Solicitação Enviada com sucesso");
        } else {
            System.out.println("Não foi possível enviar a solicitação");
        }
        Tela_ListaSolicitacoes telaLista = new Tela_ListaSolicitacoes();
        telaLista.setVisible(true);
        dispose();
    }//GEN-LAST:event_confirmarSolicitacaiButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        Painel_Corretor painelCorretor = new Painel_Corretor();
        painelCorretor.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_EnviarSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_EnviarSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_EnviarSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_EnviarSolicitacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_EnviarSolicitacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxAnoSolicitacao;
    private javax.swing.JComboBox<String> ComboBoxAnoVisita;
    private javax.swing.JComboBox<String> ComboBoxDiaSolicitacao;
    private javax.swing.JComboBox<String> ComboBoxDiaVisita1;
    private javax.swing.JComboBox<String> ComboBoxMesSolicitacao;
    private javax.swing.JComboBox<String> ComboBoxMesVisita;
    private javax.swing.JComboBox<String> ComboBoxNivelEstruturaAmeacada1;
    private javax.swing.JComboBox<String> ComboBoxNivelLocalzacaoPerigosa1;
    private javax.swing.JComboBox<String> ComboBoxNivelTerrenoPerigosa1;
    private javax.swing.JComboBox<String> ComboBoxResultadoSolicitacao;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton confirmarSolicitacaiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane motivoReprovacao;
    private javax.swing.JTextField valorSolicitacao;
    // End of variables declaration//GEN-END:variables
}
