/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ResidenciaDAO;
import dadosResidencia.Residencia;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Matheus Montanha
 */
public class Tela_DadosResidencia extends javax.swing.JFrame {

    /**
     * Creates new form Tela_DadosResidencia
     */
    public Tela_DadosResidencia() {
        initComponents();
        ResidenciaDAO dao = new ResidenciaDAO();
        List<Residencia> listaDeResidencias;
        listaDeResidencias = dao.read();
        String cep = "" + listaDeResidencias.get(0).getCepRes();
        String rua = "" + listaDeResidencias.get(0).getRuaRes();
        campoCepResidencia.setText(cep);
        campoRuaResidencia.setText(rua);
        campoLocalizacaoPerigosa.setText("" + listaDeResidencias.get(0).getLocalizacaoPerigosa());
        campoTerrenoPerigoso.setText("" + listaDeResidencias.get(0).getTerrenoPerigoso());
        campoEstruturaAmeacada.setText("" + listaDeResidencias.get(0).getEstruturaAmeacada());
        campoDescricaoResidencia.setText("" + listaDeResidencias.get(0).getDescricaoRes());
        campoUFResidencia.setText(listaDeResidencias.get(0).getufResidencia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCepResidencia = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jLabelRua = new javax.swing.JLabel();
        campoRuaResidencia = new javax.swing.JTextField();
        jLabelLocaliPerigosa = new javax.swing.JLabel();
        jLabelTerrenoPerigo = new javax.swing.JLabel();
        jLabelEstruturaAmea = new javax.swing.JLabel();
        campoLocalizacaoPerigosa = new javax.swing.JTextField();
        campoTerrenoPerigoso = new javax.swing.JTextField();
        campoEstruturaAmeacada = new javax.swing.JTextField();
        jLabelDescr = new javax.swing.JLabel();
        campoDescricaoResidencia = new javax.swing.JTextField();
        jLabelUF = new javax.swing.JLabel();
        campoUFResidencia = new javax.swing.JTextField();
        ButtonContratarSeguro = new javax.swing.JButton();
        buttonRecusarSeguro = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoCepResidencia.setEditable(false);
        getContentPane().add(campoCepResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, 30));

        jLabelCep.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelCep.setText("Cep:");
        getContentPane().add(jLabelCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 30, -1));

        jLabelRua.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelRua.setText("Rua:");
        getContentPane().add(jLabelRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        campoRuaResidencia.setEditable(false);
        getContentPane().add(campoRuaResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 200, 30));

        jLabelLocaliPerigosa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelLocaliPerigosa.setText("Localização Perigosa:");
        getContentPane().add(jLabelLocaliPerigosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 30));

        jLabelTerrenoPerigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelTerrenoPerigo.setText("Terreno Perigoso:");
        getContentPane().add(jLabelTerrenoPerigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 110, 30));

        jLabelEstruturaAmea.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelEstruturaAmea.setText("Estrutura Ameaçada:");
        getContentPane().add(jLabelEstruturaAmea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 30));

        campoLocalizacaoPerigosa.setEditable(false);
        getContentPane().add(campoLocalizacaoPerigosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 30, 30));

        campoTerrenoPerigoso.setEditable(false);
        getContentPane().add(campoTerrenoPerigoso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 30, 30));

        campoEstruturaAmeacada.setEditable(false);
        getContentPane().add(campoEstruturaAmeacada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 30, 30));

        jLabelDescr.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelDescr.setText("Descrição:");
        getContentPane().add(jLabelDescr, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 70, 20));

        campoDescricaoResidencia.setEditable(false);
        getContentPane().add(campoDescricaoResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 120, 30));

        jLabelUF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabelUF.setText("UF:");
        getContentPane().add(jLabelUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 20, -1));

        campoUFResidencia.setEditable(false);
        getContentPane().add(campoUFResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 120, 30));

        ButtonContratarSeguro.setBackground(new java.awt.Color(0, 153, 255));
        ButtonContratarSeguro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonContratarSeguro.setForeground(new java.awt.Color(255, 255, 255));
        ButtonContratarSeguro.setText("Aprovada");
        ButtonContratarSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonContratarSeguroActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonContratarSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 100, 30));

        buttonRecusarSeguro.setBackground(new java.awt.Color(204, 0, 0));
        buttonRecusarSeguro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonRecusarSeguro.setForeground(new java.awt.Color(255, 255, 255));
        buttonRecusarSeguro.setText("Recusada");
        buttonRecusarSeguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRecusarSeguroActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRecusarSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 100, 30));

        voltarButton.setBackground(new java.awt.Color(0, 153, 255));
        voltarButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back.png"))); // NOI18N
        voltarButton.setText("      Voltar");
        voltarButton.setToolTipText("");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Cidade:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 120, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem Título-1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonContratarSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonContratarSeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonContratarSeguroActionPerformed

    private void buttonRecusarSeguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRecusarSeguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRecusarSeguroActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        Tela_ListaSolicitacoes telaLista = new Tela_ListaSolicitacoes();
        telaLista.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_DadosResidencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_DadosResidencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_DadosResidencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_DadosResidencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_DadosResidencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonContratarSeguro;
    private javax.swing.JButton buttonRecusarSeguro;
    public javax.swing.JTextField campoCepResidencia;
    public javax.swing.JTextField campoDescricaoResidencia;
    public javax.swing.JTextField campoEstruturaAmeacada;
    public javax.swing.JTextField campoLocalizacaoPerigosa;
    public javax.swing.JTextField campoRuaResidencia;
    public javax.swing.JTextField campoTerrenoPerigoso;
    public javax.swing.JTextField campoUFResidencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelCep;
    public javax.swing.JLabel jLabelDescr;
    public javax.swing.JLabel jLabelEstruturaAmea;
    public javax.swing.JLabel jLabelLocaliPerigosa;
    public javax.swing.JLabel jLabelRua;
    public javax.swing.JLabel jLabelTerrenoPerigo;
    public javax.swing.JLabel jLabelUF;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
