/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DadosUsuarios.Segurado;
import Motor.Gerenciador;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Montanha
 */
public class Tela_DadosSinistro extends javax.swing.JFrame {

    /**
     * Creates new form Tela_DadosSinistro
     *
     * @param selecionado
     */
    public Tela_DadosSinistro(int selecionado) {
        initComponents();
        Gerenciador motor = new Gerenciador();
        List<Segurado> listaSinistro = motor.listaDeSinistrosPendentes();
        campoDataSinistro.setText("" + listaSinistro.get(selecionado).getSinistros().get(selecionado).getDataSinistro());
        campoDescricaoSinistro.setText(listaSinistro.get(selecionado).getSinistros().get(selecionado).getDescricaoSinistro());
        campoTipoSinistro.setText(listaSinistro.get(selecionado).getSinistros().get(selecionado).getTipoSinistro());
        campoValorSinistro.setText("" + listaSinistro.get(selecionado).getSinistros().get(selecionado).getValorSinistro());
        campoNomeSolicitante.setText(listaSinistro.get(selecionado).getNomePessoa());
        campoCPFSolicitante.setText("" + listaSinistro.get(selecionado).getCpf());
        campoEmailSolicitante.setText(listaSinistro.get(selecionado).getEmail());
        campoTelefone.setText(listaSinistro.get(selecionado).getTelefone());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        voltarButton = new javax.swing.JButton();
        ButtonAutorizarPagamento = new javax.swing.JButton();
        buttonNegarPagamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoDataSinistro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoValorSinistro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoTipoSinistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescricaoSinistro = new javax.swing.JTextArea();
        campoNomeSolicitante = new javax.swing.JTextField();
        campoCPFSolicitante = new javax.swing.JTextField();
        campoEmailSolicitante = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/esse sim.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarButton.setBackground(new java.awt.Color(0, 153, 255));
        voltarButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back2.png"))); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 30));

        ButtonAutorizarPagamento.setBackground(new java.awt.Color(0, 153, 255));
        ButtonAutorizarPagamento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonAutorizarPagamento.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAutorizarPagamento.setText("Autorizar Pagamento");
        ButtonAutorizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAutorizarPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAutorizarPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 160, 30));

        buttonNegarPagamento.setBackground(new java.awt.Color(153, 51, 255));
        buttonNegarPagamento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonNegarPagamento.setForeground(new java.awt.Color(255, 255, 255));
        buttonNegarPagamento.setText("Negar Pagamento");
        buttonNegarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNegarPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonNegarPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 140, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Descrição:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 70, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Data:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 30, 20));

        campoDataSinistro.setEditable(false);
        campoDataSinistro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoDataSinistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataSinistroActionPerformed(evt);
            }
        });
        getContentPane().add(campoDataSinistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 90, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Valor: R$");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 110, 50));

        campoValorSinistro.setEditable(false);
        campoValorSinistro.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        campoValorSinistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(campoValorSinistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 90, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Tipo do Sinistro:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        campoTipoSinistro.setEditable(false);
        campoTipoSinistro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(campoTipoSinistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 130, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Dados do Sinistro:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 10, 340));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Dados do Solicitante:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Nome:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("CPF:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 40, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Telefone:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 60, -1));

        campoDescricaoSinistro.setEditable(false);
        campoDescricaoSinistro.setColumns(20);
        campoDescricaoSinistro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        campoDescricaoSinistro.setRows(5);
        jScrollPane1.setViewportView(campoDescricaoSinistro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        campoNomeSolicitante.setEditable(false);
        campoNomeSolicitante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(campoNomeSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 200, 30));

        campoCPFSolicitante.setEditable(false);
        campoCPFSolicitante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(campoCPFSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 200, 30));

        campoEmailSolicitante.setEditable(false);
        campoEmailSolicitante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(campoEmailSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 200, 30));

        campoTelefone.setEditable(false);
        campoTelefone.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 200, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 10, 330));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("Avaliador:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Parecer:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 296, 210, 90));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Preencha o campo abaixo.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem Título-1.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja retornar a lista de solicitações de sinistro?");
        if (resposta == 0) {
            Tela_ListaSolicitacoes telaLista = new Tela_ListaSolicitacoes();
            telaLista.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void ButtonAutorizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAutorizarPagamentoActionPerformed
        JOptionPane.showConfirmDialog(rootPane, "Pagamento de sinistro autorizado com sucesso!", "Confirmação", JOptionPane.CLOSED_OPTION);
        Tela_ListaDeSinistro listSinistros = new Tela_ListaDeSinistro();
        listSinistros.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonAutorizarPagamentoActionPerformed

    private void buttonNegarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNegarPagamentoActionPerformed
        int controle = 0;
        while (controle == 0) {
            String motivo = JOptionPane.showInputDialog(rootPane, "Digite o motivo da rejeição do sinistro, por favor:");
            if (motivo.equalsIgnoreCase("") || motivo.equalsIgnoreCase(" ")) {
                JOptionPane.showConfirmDialog(rootPane, "O campo de texto não deve ser deixado em branco."
                        + " Por favor, preencha novamente!", "Alerta", JOptionPane.CLOSED_OPTION);
            } else {
                controle = 1;
            }
        }
    }//GEN-LAST:event_buttonNegarPagamentoActionPerformed

    private void campoDataSinistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataSinistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataSinistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_DadosSinistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_DadosSinistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_DadosSinistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_DadosSinistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int selecionado = 0;
                new Tela_DadosSinistro(selecionado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAutorizarPagamento;
    private javax.swing.JButton buttonNegarPagamento;
    private javax.swing.JTextField campoCPFSolicitante;
    private javax.swing.JTextField campoDataSinistro;
    private javax.swing.JTextArea campoDescricaoSinistro;
    private javax.swing.JTextField campoEmailSolicitante;
    private javax.swing.JTextField campoNomeSolicitante;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JTextField campoTipoSinistro;
    private javax.swing.JTextField campoValorSinistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
