-- MySQL Script generated by MySQL Workbench
-- Fri Apr 27 21:09:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema seguroderesidencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seguroderesidencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seguroderesidencia` DEFAULT CHARACTER SET utf8 ;
USE `seguroderesidencia` ;

-- -----------------------------------------------------
-- Table `seguroderesidencia`.`nivelPericulosidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`nivelPericulosidade` (
  `terrenoPerigoso` VARCHAR(10) NULL DEFAULT NULL,
  `estruturaAmeacada` VARCHAR(10) NULL DEFAULT NULL,
  `idNivelP` INT NOT NULL AUTO_INCREMENT,
  `localizaçãoPerigosa` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idNivelP`),
  UNIQUE INDEX `idNivelP_UNIQUE` (`idNivelP` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`local` (
  `bairro` VARCHAR(45) NULL DEFAULT NULL,
  `uf` VARCHAR(2) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idLocal`),
  UNIQUE INDEX `idLocal_UNIQUE` (`idLocal` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`candidato` (
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `dataNascimento` DATETIME NULL DEFAULT NULL,
  `idPessoa` INT NOT NULL,
  `idLocal` INT NOT NULL,
  INDEX `fk_candidatoLocal` (`idLocal` ASC),
  UNIQUE INDEX `idLocal_UNIQUE` (`idLocal` ASC),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC),
  CONSTRAINT `fk_candidatoLocal`
    FOREIGN KEY (`idLocal`)
    REFERENCES `seguroderesidencia`.`local` (`idLocal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`residencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`residencia` (
  `quantidadeGaragens` DECIMAL(45) NULL DEFAULT NULL,
  `anoConstrucao` DATETIME NULL DEFAULT NULL,
  `ufResidencia` VARCHAR(2) NULL DEFAULT NULL,
  `idResidencia` INT NOT NULL AUTO_INCREMENT,
  `quantidadeComodos` DECIMAL(45) NULL DEFAULT NULL,
  `descricaoResidencia` VARCHAR(145) NULL DEFAULT NULL,
  `areaTotal` VARCHAR(45) NULL DEFAULT NULL,
  `cepResidencia` VARCHAR(10) NULL DEFAULT NULL,
  `areaConstruida` VARCHAR(45) NULL DEFAULT NULL,
  `numeroAndares` DECIMAL(45) NULL DEFAULT NULL,
  `enderecoResidencia` VARCHAR(45) NULL DEFAULT NULL,
  `idNivelP` INT NULL DEFAULT NULL,
  `idLocal` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idResidencia`),
  INDEX `fk_nivelPResidencia` (`idNivelP` ASC),
  UNIQUE INDEX `idResidencia_UNIQUE` (`idResidencia` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`pessoa` (
  `Nome` VARCHAR(45) NULL DEFAULT NULL,
  `Endereco` VARCHAR(45) NULL DEFAULT NULL,
  `Telefone` BIGINT(12) NULL DEFAULT NULL,
  `Cpf` VARCHAR(14) NULL DEFAULT NULL,
  `nomeLogin` VARCHAR(10) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC));


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`solicitacao` (
  `idSolicitacao` INT NOT NULL AUTO_INCREMENT,
  `dataSolicitacao` DATETIME NULL DEFAULT NULL,
  `dataVisitaResidenciia` DATETIME NULL DEFAULT NULL,
  `valorSolicitacao` DECIMAL(10) NULL DEFAULT NULL,
  `aprovada` VARCHAR(10) NULL DEFAULT NULL,
  `motivoReprovacao` VARCHAR(150) NULL DEFAULT NULL,
  `idResidencia` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`idSolicitacao`),
  INDEX `fk_solicitacaoResidencia` (`idResidencia` ASC),
  UNIQUE INDEX `idSolicitacao_UNIQUE` (`idSolicitacao` ASC),
  CONSTRAINT `fk_solicitacaoResidencia`
    FOREIGN KEY (`idResidencia`)
    REFERENCES `seguroderesidencia`.`residencia` (`idResidencia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_solicitacaoPessoa`
    FOREIGN KEY ()
    REFERENCES `seguroderesidencia`.`pessoa` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`corretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`corretor` (
  `ativoCorretor` VARCHAR(10) NULL DEFAULT NULL,
  `dataContratacao` DATETIME NULL DEFAULT NULL,
  `idPessoa` INT NOT NULL,
  INDEX `fk_corretorPessoa_idx` (`idPessoa` ASC),
  CONSTRAINT `fk_corretorPessoa`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `seguroderesidencia`.`pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`analiseSolicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`analiseSolicitacao` (
  `idCorretor` INT NOT NULL,
  `idSolicitacao` INT NOT NULL,
  `data` DATE NULL,
  INDEX `fk_solicitacao` (`idSolicitacao` ASC),
  UNIQUE INDEX `idSolicitacao_UNIQUE` (`idSolicitacao` ASC),
  UNIQUE INDEX `idCorretor_UNIQUE` (`idCorretor` ASC),
  CONSTRAINT `fk_solicitacao`
    FOREIGN KEY (`idSolicitacao`)
    REFERENCES `seguroderesidencia`.`solicitacao` (`idSolicitacao`),
  CONSTRAINT `fk_corretor`
    FOREIGN KEY (`idCorretor`)
    REFERENCES `seguroderesidencia`.`corretor` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`tipoSinistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`tipoSinistro` (
  `descricaoTipoSinistro` VARCHAR(45) NULL DEFAULT NULL,
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idTipo`),
  UNIQUE INDEX `idTipo_UNIQUE` (`idTipo` ASC));


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`sinistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`sinistro` (
  `parecerAvaliador` VARCHAR(145) NULL DEFAULT NULL,
  `dataSinistro` DATETIME NULL DEFAULT NULL,
  `descricaoSinistro` VARCHAR(145) NULL DEFAULT NULL,
  `autorizadoSinistro` VARCHAR(10) NULL DEFAULT NULL,
  `valorSinistro` DECIMAL(45) NULL DEFAULT NULL,
  `idSinistro` INT NOT NULL AUTO_INCREMENT,
  `idTipo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idSinistro`),
  UNIQUE INDEX `idSinistro_UNIQUE` (`idSinistro` ASC),
  CONSTRAINT `fk_tipoSinistro`
    FOREIGN KEY (`idTipo`)
    REFERENCES `seguroderesidencia`.`tipoSinistro` (`idTipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`avaliaSinistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`avaliaSinistro` (
  `idSinistro` INT NULL DEFAULT NULL,
  `dataAvalicao` DATE NULL,
  `observacaoSinistro` VARCHAR(45) NULL,
  INDEX `fk_avaliacaoSinistro` (`idSinistro` ASC),
  CONSTRAINT `fk_avaliacaoSinistro`
    FOREIGN KEY (`idSinistro`)
    REFERENCES `seguroderesidencia`.`sinistro` (`idSinistro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`apolice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`apolice` (
  `idApolice` INT NOT NULL AUTO_INCREMENT,
  `bandeiraCartao` CHAR(10) NULL DEFAULT NULL,
  `numeroApolice` FLOAT NULL DEFAULT NULL,
  `premioApolice` DECIMAL(45) NULL DEFAULT NULL,
  `dataContratacaoApolice` DATETIME NULL DEFAULT NULL,
  `cartaoCreditoPgto` BIGINT(45) NULL DEFAULT NULL,
  `vencimentoCartao` DATETIME NULL DEFAULT NULL,
  `codSegurancaCartao` DECIMAL(10) NULL DEFAULT NULL,
  `nomeNoCartao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idApolice`),
  UNIQUE INDEX `idApolice_UNIQUE` (`idApolice` ASC));


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`apoliceParcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`apoliceParcela` (
  `idApolice` INT NULL DEFAULT NULL,
  `idParcela` INT NULL DEFAULT NULL,
  INDEX `fk_parecla_idx` (`idParcela` ASC),
  INDEX `fk_apolice_idx` (`idApolice` ASC),
  CONSTRAINT `fk_parecla`
    FOREIGN KEY (`idParcela`)
    REFERENCES `seguroderesidencia`.`parcelaApolice` (`idParcela`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_apolice`
    FOREIGN KEY (`idApolice`)
    REFERENCES `seguroderesidencia`.`apolice` (`idApolice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`servico` (
  `descricaoServico` VARCHAR(145) NULL DEFAULT NULL,
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `quantidadeServico` DECIMAL(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idServico`),
  UNIQUE INDEX `idServico_UNIQUE` (`idServico` ASC));


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`itemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`itemServico` (
  `descricaoRecusa` VARCHAR(145) NULL DEFAULT NULL,
  `descricaoAtendimento` VARCHAR(145) NULL DEFAULT NULL,
  `dataAtendimento` DATETIME NULL DEFAULT NULL,
  `atendidaSolicitacao` VARCHAR(10) NULL DEFAULT NULL,
  `aceitaSolicitacao` VARCHAR(10) NULL DEFAULT NULL,
  `descricaoSolicitacao` VARCHAR(145) NULL DEFAULT NULL,
  `dataSolicitacao` DATETIME NULL DEFAULT NULL,
  `idItemServiço` INT NOT NULL AUTO_INCREMENT,
  `idServico` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idItemServiço`),
  UNIQUE INDEX `idItemServiço_UNIQUE` (`idItemServiço` ASC));


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`RelataSinistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`RelataSinistro` (
  `idSinistro` INT NULL DEFAULT NULL,
  `idPessoa` INT NULL DEFAULT NULL,
  INDEX (`idSinistro` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`idSinistro`)
    REFERENCES `seguroderesidencia`.`sinistro` (`idSinistro`));


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`segurado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`segurado` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  INDEX (`idPessoa` ASC),
  CONSTRAINT `fk_candidato`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `seguroderesidencia`.`candidato` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`seguradoApolice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`seguradoApolice` (
  `idApolice` INT NOT NULL,
  `idPessoa` INT NOT NULL,
  INDEX `fk_apolice` (`idApolice` ASC),
  INDEX `fk_segurado` (`idPessoa` ASC),
  CONSTRAINT `fk_apolice`
    FOREIGN KEY (`idApolice`)
    REFERENCES `seguroderesidencia`.`apolice` (`idApolice`),
  CONSTRAINT `fk_segurado`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `seguroderesidencia`.`segurado` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`solicitaServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`solicitaServico` (
  `idItemServico` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `idItemServiço_UNIQUE` (`idItemServico` ASC));


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`bem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`bem` (
  `valorEstimadoBem` DECIMAL(45) NULL DEFAULT NULL,
  `descricaoBem` VARCHAR(145) NULL DEFAULT NULL,
  `idBem` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idBem`),
  UNIQUE INDEX `idBem_UNIQUE` (`idBem` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`bemResidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`bemResidencia` (
  `idResidencia` INT NOT NULL,
  `idBem` INT NOT NULL,
  INDEX `fk_bemResidencia_residencia` (`idResidencia` ASC),
  UNIQUE INDEX `idResidencia_UNIQUE` (`idResidencia` ASC),
  UNIQUE INDEX `idBem_UNIQUE` (`idBem` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `seguroderesidencia`.`parcelaApolice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguroderesidencia`.`parcelaApolice` (
  `idParcela` INT NOT NULL AUTO_INCREMENT,
  `dataPgt` DATE NULL,
  `valorParcela` FLOAT NULL,
  `qntParcelas` INT(10) NULL,
  PRIMARY KEY (`idParcela`),
  UNIQUE INDEX `idParcela_UNIQUE` (`idParcela` ASC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
